services:
  - type: web
    name: varecvsce
    runtime: node
    buildCommand: bash render-build.sh
    startCommand: node --enable-source-maps ./artifacts/api-server/dist/index.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
